### ISSUE TITLE
Install Sentry

### ISSUE THREAD

**Issue by xefke** [xefke/SEBC#7]

**Comment by xefke** [comment]
Hi, I have not been able to provide the beeswax screenshot.
But I have the screenshot for beeline, however, it was hard to screenshot the command line.
Therefore, the output is also in 6_sentry_install.md together with the proof that I was able to install sentry, provide the roles and attach the roles to the groups.
I added the statement of the 10 rows in HUE as well for readability (6_HUE_table_nimbus.png)

I added the proof of the login per user with each of its own table showing.
I hope this is enough to show you I know the matter.

**Comment by mfernest** [comment]
This is fine. I don't know what I was thinking when I asked for a screenshot of a terminal session. Bleh.

The rest of your work here more than makes up for what I requested. 🏆
